NTierProject.WebUI/Areas/Admin/Controllers/AppUserController.cs
using NtierProject.SERVICE.Option;
using NTierProject.COMMON.MyTools;
using NTierProject.MODEL.Entities;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTierProject.WebUI.Areas.Admin.Controllers
{
    public class AppUserController : Controller
    {
        AppUserService appUserService = new AppUserService();
        public ActionResult Index()
        {
            return View(appUserService.GetActive().OrderByDescending(x => x.CreatedDate).ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AppUser model, HttpPostedFileBase ImagePath)
        {
            model.ID = Guid.NewGuid();
            model.ImagePath = ImageUploader.UploadSingleImage("~/Uploads/Users/", ImagePath);
            model.Password = model.ConfirmPassword = Guid.NewGuid().ToString();
            model.isActive = true;

            appUserService.Add(model);
            MailSender.Send(model.Email, "Sayın " + model.Name + " " + model.SurName + "," + "\n" + "İsteğiniz üzerine hesabınız açılmıştır." + "\n" + "Şifreniz: " + model.Password + "\n" + "\n" + "Giriş yaptıktan sonra lütfen şifrenizi değiştiriniz!", "Sitemize Hoşgeldiniz");
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid Id)
        {
            return View(appUserService.GetById(Id));
        }

        [HttpPost]
        public ActionResult Edit(AppUser appUser, HttpPostedFileBase ImagePath)
        {
            string cEmailMsg = null;

            if (appUserService.CheckAgainEmailAddres(appUser, out string msgMail, out AppUser appMailUserout, out cEmailMsg))
            {
                TempData["Error"] = msgMail;
                return View(appMailUserout);
            }

            appUserService.CheckImageFullEmpty(appUser, ImagePath, cEmailMsg);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid Id)
        {
            return View(appUserService.GetById(Id));
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid Id)
        {
            appUserService.Remove(appUserService.GetById(Id));
            return RedirectToAction("Index");
        }

        public ActionResult ResetPassword(Guid id)
        {
            AppUser user = appUserService.GetById(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("ResetPassword")]
        [ValidateAntiForgeryToken]
        public ActionResult ResetPasswordConfirmed(Guid id)
        {
            AppUser user = appUserService.GetById(id);
            user.Password = user.ConfirmPassword = Guid.NewGuid().ToString();

            //TODO: Session veya cookie tanımlandığında değiştirenin id veya mail adresi ModifiedBy'a verilecek.
            //user.ModifiedBy = Email;
            appUserService.Update(user);

            MailSender.Send(user.Email, "Sayın " + user.Name + " " + user.SurName + "," + "\n" + "İsteğiniz üzerine şifreniz sıfırlandı." + "\n" + "Yeni Şifreniz: " + user.Password + "\n" + "\n" + "Giriş yaptıktan sonra lütfen şifrenizi değiştiriniz!", "Şifreniz sıfırlandı");
            return RedirectToAction("Index");
        }
    }
}

NTierProject.WebUI/Controllers/ProductController.cs
using NtierProject.SERVICE.Option;
using System;
using System.Web.Mvc;

namespace NTierProject.WebUI.Controllers
{
    public class ProductController : Controller
    {
        ProductService ps;
        public ProductController()
        {
            ps = new ProductService();
        }

        public ActionResult Index()
        {
            try
            {
                return View(ps.GetActive());
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

NTierProject.WebUI/Areas/Admin/Views/AppUser/Create.cshtml
@model AppUser
@{
    ViewBag.Title = "Kullanıcı Ekle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@ViewBag.Title</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Create", "AppUser", FormMethod.Post, new { @class = "form-signin", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SurName, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.SurName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SurName, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label" })
                    <select class="form-control" id="Role" name="Role">
                        @foreach (var item in Enum.GetValues(typeof(Role)))
                        {
                            if ((Role)item == Role.Member)
                            {
                                <option selected>@item</option>
                            }
                            else
                            {
                                <option>@item</option>
                            }
                        }
                    </select>
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label" })
                    <input type="file" class="form-control" name="ImagePath" required />
                    @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2">
                        <input type="submit" value="Kaydet" class="btn btn-lg btn-block btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Tüm Kullanıcılara Geri Dön", "Index")
</div>

NTierProject.WebUI/Areas/Admin/Views/AppUser/Delete.cshtml
@model NTierProject.MODEL.Entities.AppUser

@{
    ViewBag.Title = "Kullanıcı Sil";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@Model.Name - @ViewBag.Title</h6>
    </div>
    <div class="card-body">
        <h2>@Model.Name  @Model.SurName (@Model.Email) isimli hesap silinsin mi?</h2>
        <div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <input type="submit" value="Sil" class="btn-danger" />
                </div>
            }
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Kullanıcı Listesine Geri Dön", "Index")
</div>

NTierProject.WebUI/Areas/Admin/Views/AppUser/Edit.cshtml
@using NTierProject.CORE.Enums
@model AppUser
@{
    ViewBag.Title = "Kullanıcı Düzenle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@ViewBag.Title</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Create", "Product", FormMethod.Post, new { @class = "form-signin", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SurName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.SurName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SurName, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <a href="@Url.Action("ResetPassword", "AppUser", new { id=Model.ID })" class="btn btn-warning">Şifreyi Sıfırla</a>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label" })
                <select class="form-control" id="Role" name="Role">
                    @foreach (var item in Enum.GetValues(typeof(Role)))
                    {
                        if ((Role)item == Model.Role)
                        {
                            <option selected>@item</option>
                        }
                        else
                        {
                            <option>@item</option>
                        }
                    }
                </select>
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <img src="@Model.ImagePath" style="width:64px; height:64px" />
            </div>
            <div class="form-group">
                <label for="ImagePath">Görsel Seç</label>
                <input type="file" class="form-control" id="ImagePath" name="ImagePath" />
            </div>

            <div class="form-group">
                <div class="col-md-offset-2">
                    <input type="submit" value="Kaydet" class="btn btn-lg btn-block btn-success" />
                </div>
            </div>
        </div>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Tüm Kullanıcılara Geri Dön", "Index")
</div>

NTierProject.WebUI/Areas/Admin/Views/AppUser/Index.cshtml
@using NTierProject.CORE.Enums
@model List<AppUser>
@{
    ViewBag.Title = "Kullanıcılar";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@ViewBag.Title</h6>
        @Html.ActionLink("Yeni Kullanıcı Ekle", "Create", null, new { @class = "pull-right-mycss" })
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Görsel</th>
                        <th>Adı</th>
                        <th>Soyadı</th>
                        <th>Kullanıcı Adı</th>
                        <th>Email</th>
                        <th>Adres</th>
                        <th>Telefon</th>
                        <th>Doğum Tarihi</th>
                        <th>Seviye</th>
                        <th>Aktif/Pasif</th>
                        <th>Oluşturma Tarihi</th>
                        <th>Düzenle</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Görsel</th>
                        <th>Adı</th>
                        <th>Soyadı</th>
                        <th>Kullanıcı Adı</th>
                        <th>Email</th>
                        <th>Adres</th>
                        <th>Telefon</th>
                        <th>Doğum Tarihi</th>
                        <th>Seviye</th>
                        <th>Aktif/Pasif</th>
                        <th>Oluşturma Tarihi</th>
                        <th>Düzenle</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <img src="@item.ImagePath" class="img-sm-mycss" />
                            </td>
                            <td>@item.Name</td>
                            <td>@item.SurName</td>
                            <td>@item.UserName</td>
                            <td>@item.Email</td>
                            <td>@item.Address</td>
                            <td>@item.PhoneNumber</td>
                            <td>@(((DateTime)item.BirthDate).ToShortDateString())</td>
                            @if (item.Role == Role.Banned)
                            {
                                <td>Yasaklı</td>
                            }
                            else if (item.Role == Role.Member)
                            {
                                <td>Üye</td>
                            }
                            else
                            {
                                <td>Yönetici</td>
                            }

                            @if (item.isActive)
                            {
                                <td>Aktif</td>
                            }
                            else
                            {
                                <td>Pasif</td>
                            }
                            <td>@item.CreatedDate</td>
                            <td>
                                @Html.ActionLink("Düzenle", "Edit", new { id = item.ID }, new { @class = "btn btn-primary" }) |
                                @Html.ActionLink("Sil", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" }) |
                                @Html.ActionLink("Şifreyi Sıfırla", "ResetPassword", new { id = item.ID }, new { @class = "btn btn-warning" }) 
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

NTierProject.WebUI/Areas/Admin/Views/AppUser/ResetPassword.cshtml
@model AppUser
@{
    ViewBag.Title = Model.Name + " " + Model.SurName + " (" + Model.Email + ")" + " İsimli Kullanıcının Şifresini Sıfırla";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@Model.Name - @ViewBag.Title</h6>
    </div>
    <div class="card-body">
        <h2>@Model.Name  @Model.SurName (@Model.Email) isimli hesabın şifresi sıfırlansın mı?</h2>
        <div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <input type="submit" value="Şifreyi Sıfırla" class="btn btn-danger" />
                </div>
            }
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Kullanıcı Listesine Geri Dön", "Index")
</div>