NTierProject.WebUI/Areas/Admin/Controllers/OrderDetailController.cs
using NtierProject.SERVICE.Option;
using NTierProject.MODEL.Entities;
using System;
using System.Net;
using System.Web.Mvc;

// TODO: 1  Detail listeleme, ekleme ve gücellemem yapılmamıştır

namespace NTierProject.WebUI.Areas.Admin.Controllers
{
    public class OrderDetailController : Controller
    {
        OrderService order = new OrderService();
        OrderDetailService orderDetail = new OrderDetailService();
        public ActionResult Index()
        {
            return View(orderDetail.GetActive());
        }

        public ActionResult Add()
        {
            return View(order.GetActive());
        }

        [HttpPost]
        public ActionResult Add(OrderDetail data)
        {
            data.ID = Guid.NewGuid();
            orderDetail.Add(data);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderDetail od = orderDetail.GetById(id);
            if (od == null)
            {
                return HttpNotFound();
            }
            return View(od);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            OrderDetail od = orderDetail.GetById(id);
            orderDetail.Remove(od);
            return RedirectToAction("Index");
        }
    }
}

NTierProject.WebUI/Areas/Admin/Views/OrderDetail/Add.cshtml
@model List<Order>
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-6">
    <section class="panel">
        <header class="panel-heading">
            @ViewBag.Title
        </header>
        <form method="post" action="/Admin/OrderDetail/Add">
            <div class="form-group">
                <label>Birim Fiyat</label>
                <input type="text" class="form-control" name="UnitPrice" placeholder="Birim fiyatını giriniz." />
            </div>
            <div class="form-group">
                <label>Mikar</label>
                <input type="text" class="form-control" name="Quantity" placeholder="Açıklama girin." />
            </div>
            <div class="form-group">
                <label>Siparis Seçin</label>
                <select class="form-control" name="ID">
                    @foreach (var item in Model)
                    {
                        <option value="@item.ID">@item.ID</option>
                    }
                </select>
            </div>
            <button type="submit" class="btn btn-info">Gönder</button>
        </form>
    </section>
</div>

NTierProject.WebUI/Areas/Admin/Views/OrderDetail/Delete.cshtml
@model NTierProject.MODEL.Entities.OrderDetail
@{
    ViewBag.Title = "Sil";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Şiparis Detayı</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedComputerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedComputerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedIP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedIP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedADUsername)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedADUsername)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedComputerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedComputerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedIP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedIP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedADUsername)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedADUsername)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NTierProject.WebUI/Areas/Admin/Views/OrderDetail/Index.cshtml
@model List<OrderDetail>
@{
    ViewBag.Title = "Sipariş Detail";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">@ViewBag.Title</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Miktar</th>
                        <th>Birim Fiyat</th>
                        <th>Düzenle</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Miktar</th>
                        <th>Birim Fiyat</th>
                        <th>Düzenle</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Quantity</td>
                        <td>@item.UnitPrice</td>
                        <td>
                            <a href="@Url.Action("Update","OrderDetail",new { id=item.ID})"><i class="icon-pencil"></i></a>
                            |
                            <a href="@Url.Action("Delete","OrderDetail",new { id=item.ID})"><i class="icon-trash"></i></a>
                        </td>
                    </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>