NTierProject.WebUI/Areas/Admin/Controllers/OrderController.cs
using NtierProject.SERVICE.Option;
using NTierProject.MODEL.Entities;
using System;
using System.Net;
using System.Web.Mvc;

namespace NTierProject.WebUI.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {
        OrderService db = new OrderService();
        public ActionResult Index()
        {
            return View(db.GetAll());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                order.ID = Guid.NewGuid();
                db.Add(order);
                return RedirectToAction("Index");
            }
            return View(order);
        }

        public ActionResult Update(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.GetById(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(Order order)
        {
            if (ModelState.IsValid)
            {
                order.ID = Guid.NewGuid();
                db.Update(order);
                return RedirectToAction("Index");
            }
            return View(order);
        }

        public ActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.GetById(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Order order = db.GetById(id);
            db.Remove(order);
            return RedirectToAction("Index");
        }
    }
}

NTierProject.WebUI/Controllers/CategoryController.cs
using NtierProject.SERVICE.Option;
using System;
using System.Web.Mvc;

namespace NTierProject.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        CategoryService cat;
        public CategoryController()
        {
            cat = new CategoryService();
        }

        public ActionResult Index()
        {
            try
            {
                return View(cat.GetActive());
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

NTierProject.WebUI/Controllers/ProductController.cs
using NtierProject.SERVICE.Option;
using System;
using System.Web.Mvc;

namespace NTierProject.WebUI.Controllers
{
    public class ProductController : Controller
    {
        ProductService ps;
        public ProductController()
        {
            ps = new ProductService();
        }

        public ActionResult Index()
        {
            try
            {
                return View(ps.GetActive());
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

NTierProject.WebUI/Controllers/SubCategoryController.cs
using NtierProject.SERVICE.Option;
using System;
using System.Web.Mvc;

namespace NTierProject.WebUI.Controllers
{
    public class SubCategoryController : Controller
    {
        SubCategoryService subcat;
        public SubCategoryController()
        {
            subcat = new SubCategoryService();
        }

        public ActionResult Index()
        {
            try
            {
                return View(subcat.GetActive());
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

NTierProject.WebUI/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Home")">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">E.Ticaret</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Index","Home")">
            <i class="fas fa-fw fa-home"></i>
            <span>Anasayfa</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#category"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-bars"></i>
            <span>Kategori</span>
        </a>
        <div id="category" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Kategori:</h6>
                <a class="collapse-item" href="@Url.Action("Index","Category")">Kategoriler</a>
                <a class="collapse-item" href="@Url.Action("Index","SubCategory")">Alt Kategoriler</a>
                <a class="collapse-item" href="@Url.Action("Create","Category")">Kategori Ekle</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#produtc"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-shopping-bag"></i>
            <span>Ürünler</span>
        </a>
        <div id="produtc" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Ürünler:</h6>
                <a class="collapse-item" href="@Url.Action("Index","Product")">Hepsi</a>
                <a class="collapse-item" href="@Url.Action("Create","Product")">Ürün Ekle</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#order"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-shopping-bag"></i>
            <span>Siparişler</span>
        </a>
        <div id="order" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="@Url.Action("Index","Order")">Sipariş Listesi</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#orderdetay"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-shopping-bag"></i>
            <span>Sipariş Detay</span>
        </a>
        <div id="orderdetay" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="@Url.Action("Index","OrderDetail")">Sipariş Detayları</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#user"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-users"></i>
            <span>Kullanıcılar</span>
        </a>
        <div id="user" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="@Url.Action("Index","AppUser")">Tüm Kullanıcılar</a>
                <a class="collapse-item" href="@Url.Action("Create","AppUser")">Kullanıcı Ekle</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->